#!/bin/bash

echo "Welcome $(whoami)! I am linus your linux assistant"

sleep 1
o=c
while [  $o != e    ] #check if the user wanna to make another operation or not
do
echo "Enter u to manage users ,enter fd to manage files or directories"
                                                                   
read x
if [  $x == u  ] #checking the user input
then
echo "please enter a to add new user,enter m to modify a current user,enter r to remove a current user"

read m 

if [  $m == a  ]
then
echo "Please enter the name of the user :"
read r 
sudo useradd $r 1>/dev/null
if [  $? -eq 0  ]
then
sudo passwd $r
echo "The user $r is added !"
fi

elif [ $m == m  ]
then
echo "Enter the name of the user"
read r
echo "Enter p if you want to change the password,enter s if you want to change the shell"
read t

if [ $t == p  ]
then
sudo passwd $r

elif [ $t == s  ]
then
echo "enter the shell type"
read n
sudo usermod -s $n $r
else 
echo "You have entered a wrong choice"
fi
elif [  $m == r  ]
then
echo "Enter the name of the user"
read r
id $r 1>/dev/null 2>&1
if [  $? == 0  ]
then 
sudo userdel -r $r 1>/dev/null 2>&1
echo "The user $r is deleted"
else
echo "The user $r does not exist"
fi
else 
echo "You have entered a wrong choice"
fi

elif [  $x == fd  ] #checking the user input "manage files and directories"
then
echo "Enter a to create file or directory,r to remove file or directory,c to copy file or directory,m to move file or directory" 
read v

if [  $v == a  ]
then
echo "Enter the name of the file or the directory"
read n
echo "enter f to create a file ,d to create a directory"
read p 
if [  $p == f  ] 
then
touch $n
echo "The file is created at $(pwd)/$n"
else
mkdir $n
echo "The directory is created at $(pwd)/$n"
fi
elif [  $v == r  ] 
then
echo "Enter the path of the file or the directory"
read n
rm -rf $n
echo "[$n] is removed"

elif [  $v == c  ] 
then
echo "Enter the path of the file or the directory you want to copy"
read n
 
echo "Enter where do you want to copy the file or the directory"
read z

cp -r $n $z
echo "The file is copied at $z"

elif [  $v==m  ]
then
 echo "Enter the path of the file or the directory"
 read n

echo "Enter where do you want to move the file or the directory"
read z

mv $n $Z

echo "The file is moved to $z"
else
echo "You have entered a wrong choice"
fi

else 
echo "You have entered a wrong choice"
fi

echo "Enter c to perform another operation or enter e to exit the program"
read o

done
echo "The program will be terminated in "
k=3
while [  $k -gt 0  ]
do
echo "$k"
sleep 1
k=$[k-1]
done
echo "Thank you $(whoami) for using me!"
